# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OIcGgeRuzzS8-JpWpNpYWj5IeSKQx1se
"""

pip install yfinance

import yfinance as yf
import pandas as pd


def cotizaciones_yf(tickers, fecha_inicio, fecha_final):
  df = yf.download(tickers, start=fecha_inicio, end=fecha_final,group_by="ticker")
  return df


if __name__ == "__main__":
  amzn = cotizaciones_yf("AMZN", "2021-10-03", "2021-10-05")
  amzn.to_csv('amzn_yfinance.csv', index = False)
  print(amzn)
  ticker = yf.Ticker('YPF')
  amzn_df = ticker.history(period="5y")
  amzn_df['Close'].plot(title="YPF SA stock price")